/**
 * Models shared by the server and both clients.
 *
 * Framework-free on purpose: the NestJS server, the participant client and the
 * organizer client all compile against these types, so a change to an API
 * contract breaks the build instead of a request at runtime.
 */
export {
  MAX_PASSWORD_LENGTH,
  MIN_PASSWORD_LENGTH,
  type AdminAccount,
  type AdminLoginRequest,
  type AdminSessionInfo,
} from './lib/auth';
export {
  eventSeriesStatusKey,
  eventStatusKey,
  EVENT_SERIES_STATUSES,
  EVENT_STATUSES,
  EVENT_TYPES,
  MAX_CONTENT_DESCRIPTION_LENGTH,
  MAX_CONTENT_NAME_LENGTH,
  MAX_FOLLOW_UP_LENGTH,
  MAX_VENUE_NAME_LENGTH,
  dayInZone,
  formatClockRange,
  formatDayInZone,
  formatEventPeriod,
  formatInstant,
  hasEnded,
  instantToWallClock,
  isTimeZone,
  localTimeZone,
  publicEventPath,
  publicSeriesPath,
  publicUrl,
  wallClockToInstant,
  zoneLabel,
  type EventInput,
  type EventPeriod,
  type EventSeries,
  type EventSeriesInput,
  type EventSeriesStatus,
  type EventStatus,
  type EventType,
  type OrganizerEvent,
  type PublicEvent,
  type PublicEventSeries,
} from './lib/events';
export {
  DEFAULT_PROFILE_SEARCH_PAGE_SIZE,
  MAX_ACTIVITY_AREAS_LENGTH,
  MAX_PROFILE_FIELDS,
  MAX_PROFILE_SEARCH_PAGE_SIZE,
  PROFILES_MODULE_KEY,
  PROFILE_CONFIRMATION_PATH,
  PROFILE_FIELD_TYPES,
  PROFILE_LOGIN_PATH,
  PROFILE_SEARCH_MODULE_KEY,
  type AvatarImage,
  type ParticipantAccount,
  type ParticipantLoginRequest,
  type ParticipantPasswordChange,
  type ParticipantProfileUpdate,
  type ParticipantSessionInfo,
  type ProfileConfirmation,
  type ProfileField,
  type ProfileFieldChange,
  type ProfileFieldInput,
  type ProfileFieldOrder,
  type ProfileFieldPublic,
  type ProfileFieldType,
  type ProfileRegistrationAcknowledgement,
  type ProfileRegistrationRequest,
  type ProfileSearchHit,
  type ProfileSearchPage,
  type ProfileSearchQuery,
  type PublicProfile,
} from './lib/profiles';
export {
  CHAT_CONVERSATION,
  CHAT_JOIN,
  CHAT_LEAVE,
  CHAT_MESSAGE,
  CHAT_MODULE_KEY,
  CHAT_NAMESPACE,
  CHAT_READ,
  CONVERSATION_MEMBER_TYPES,
  CONVERSATION_TYPES,
  DEFAULT_CONVERSATION_PAGE_SIZE,
  DEFAULT_MESSAGE_PAGE_SIZE,
  DEFAULT_ORGANIZER_CONVERSATION_PAGE_SIZE,
  MAX_CONVERSATION_PAGE_SIZE,
  MAX_GROUP_MEMBERS,
  MAX_GROUP_TOPIC_LENGTH,
  MAX_GUEST_EMAIL_LENGTH,
  MAX_GUEST_NAME_LENGTH,
  MAX_MESSAGE_IMAGE_BYTES,
  MAX_MESSAGE_LENGTH,
  MAX_MESSAGE_PAGE_SIZE,
  MAX_ORGANIZER_CONVERSATION_PAGE_SIZE,
  MESSAGE_IMAGE_PART,
  MESSAGE_PREVIEW_LENGTH,
  MESSAGE_SENDER_TYPES,
  ORGANIZER_CONVERSATION_TYPES,
  ORGANIZER_MESSAGES_PATH,
  PARTICIPANT_MESSAGES_PATH,
  REALTIME_PATH,
  REPLY_DELIVERIES,
  awaitsAnswer,
  organizerConversationPath,
  participantConversationPath,
  type ChatConversationEvent,
  type ChatJoinAck,
  type ChatMessage,
  type ChatReadEvent,
  type ContactRequestAcknowledgement,
  type ContactRequestInput,
  type ConversationCounterpart,
  type ConversationEventRef,
  type ConversationGuest,
  type ConversationMemberType,
  type ConversationPage,
  type ConversationPreview,
  type ConversationQuery,
  type ConversationSummary,
  type ConversationType,
  type GroupCandidate,
  type MessageHistory,
  type MessageHistoryQuery,
  type MessageSenderType,
  type NewGroupRequest,
  type OrganizerConversationDetail,
  type OrganizerConversationPage,
  type OrganizerConversationQuery,
  type OrganizerConversationSummary,
  type OrganizerConversationType,
  type OrganizerReply,
  type ReplyDelivery,
  type SendMessageInput,
  type StartConversationRequest,
} from './lib/chat';
export {
  DASHBOARD_LATEST_REGISTRATIONS,
  type EventDashboard,
  type ProgramSummary,
  type RegistrationFormSummary,
} from './lib/dashboard';
export {
  DEFAULT_PARTICIPANT_PAGE_SIZE,
  DEFAULT_PARTICIPANT_SORT,
  DEFAULT_SORT_DIRECTION,
  DEFAULT_UPLOAD_MAX_BYTES,
  MAX_CUSTOM_TEXT_LENGTH,
  MAX_FIELD_HELP_LENGTH,
  MAX_FIELD_KEY_LENGTH,
  MAX_FIELD_LABEL_LENGTH,
  MAX_FIELD_OPTIONS,
  MAX_FIELD_OPTION_LENGTH,
  MAX_FILE_FIELDS,
  MAX_FILE_NAME_LENGTH,
  MAX_PARTICIPANT_PAGE_SIZE,
  MAX_REGISTRATION_FIELDS,
  MAX_SUBMISSION_BYTES,
  MAX_UPLOAD_BYTES,
  MIN_UPLOAD_MAX_BYTES,
  PARTICIPANT_SORTS,
  REGISTRATION_FIELD_TYPES,
  REGISTRATION_PAYLOAD_PART,
  REGISTRATION_STATUSES,
  registrationStatusKey,
  UPLOAD_MIME_TYPES,
  UPLOAD_TYPES,
  acceptAttribute,
  formatAnswer,
  formatBytes,
  pageCount,
  uploadTypeLabel,
  uploadTypeLabelKey,
  type AnswerableField,
  type AnswerableFieldType,
  type AttachmentSummary,
  type ConfirmationState,
  type CustomFieldValue,
  type CustomFieldValues,
  type ParticipantDetail,
  type ParticipantPage,
  type ParticipantQuery,
  type ParticipantRow,
  type ParticipantSort,
  type RegistrationAcknowledgement,
  type RegistrationConfirmation,
  type RegistrationCounts,
  type RegistrationField,
  type RegistrationFieldChange,
  type RegistrationFieldInput,
  type RegistrationFieldOrder,
  type RegistrationFieldPublic,
  type RegistrationFieldType,
  type RegistrationInput,
  type RegistrationStatistics,
  type RegistrationStatus,
  type RegistrationStatusChange,
  type RegistrationWeek,
  type SortDirection,
  type UploadType,
} from './lib/registrations';
export {
  MAX_MEDIA_LINKS_PER_EVENT,
  MAX_MEDIA_LINK_TITLE_LENGTH,
  MAX_MEDIA_LINK_URL_LENGTH,
  MEDIA_LINKS_MODULE_KEY,
  MEDIA_LINK_KINDS,
  eventMediaLinks,
  groupMediaLinksByKind,
  isWebUrl,
  mediaLinkKindKey,
  programItemMediaLinks,
  sortMediaLinks,
  type MediaLink,
  type MediaLinkChange,
  type MediaLinkGroup,
  type MediaLinkInput,
  type MediaLinkKind,
  type MediaLinkSummary,
  type PublicMediaLink,
} from './lib/media-links';
export {
  DEFAULT_CONTACT_PAGE_SIZE,
  DEFAULT_INVITATION_PAGE_SIZE,
  INVITATION_OPT_OUT_PATH,
  MAX_CONTACT_PAGE_SIZE,
  MAX_INVITATION_BODY_LENGTH,
  MAX_INVITATION_PAGE_SIZE,
  MAX_INVITATION_RECIPIENTS,
  MAX_INVITATION_SUBJECT_LENGTH,
  invitationParagraphs,
  invitationState,
  type ContactOptOutResult,
  type ContactQuery,
  type Invitation,
  type InvitationCounts,
  type InvitationInput,
  type InvitationPage,
  type InvitationQuery,
  type InvitationState,
  type SeriesContact,
  type SeriesContactPage,
} from './lib/invitations';
export {
  MAX_PROGRAM_DESCRIPTION_LENGTH,
  MAX_PROGRAM_ITEMS,
  MAX_PROGRAM_ITEM_CAPACITY,
  MAX_PROGRAM_SPEAKER_LENGTH,
  MAX_PROGRAM_TITLE_LENGTH,
  formatProgramTime,
  groupProgramByDay,
  isProgramItemFull,
  isWithinPeriod,
  overlappingProgramItems,
  seatsLeft,
  sortProgram,
  type ProgramDay,
  type ProgramItem,
  type ProgramItemChange,
  type ProgramItemInput,
  type ProgramItemLoad,
  type ProgramItemSignup,
  type PublicProgramItem,
} from './lib/program';
export {
  DEFAULT_MY_REGISTRATION_PAGE_SIZE,
  MAX_MY_REGISTRATION_PAGE_SIZE,
  SELF_SERVICE_PATH,
  type MyProgramItem,
  type MyRegistration,
  type MyRegistrationPage,
  type MyRegistrationSummary,
} from './lib/self-service';
export {
  FALLBACK_LOCALE,
  MAX_REPORTED_IGNORED_KEYS,
  MAX_TRANSLATION_KEY_LENGTH,
  MAX_TRANSLATION_VALUE_LENGTH,
  MAX_TRANSLATION_WRITE_ENTRIES,
  isEmptyTranslation,
  isTranslationKey,
  translatedText,
  translationCompleteness,
  type EventSeriesTranslation,
  type EventSeriesTranslations,
  type EventTranslation,
  type EventTranslations,
  type LocaleCatalogueDetail,
  type LocaleOverview,
  type LocaleSummary,
  type ProgramItemTranslation,
  type ProgramItemTranslations,
  type TranslatableItem,
  type TranslatedText,
  type TranslationCatalogue,
  type TranslationEntry,
  type TranslationState,
  type TranslationWrite,
  type TranslationWriteResult,
  type TranslationsByLocale,
} from './lib/i18n';
export {
  BRANDING_IMAGE_KINDS,
  BRANDING_IMAGE_PART,
  BRANDING_MIME_TYPES,
  BRANDING_TYPES,
  DEFAULT_FONT_FAMILY_KEY,
  DEFAULT_FONT_FAMILY_STACK,
  DEFAULT_ORGANIZATION_NAME,
  FONT_FAMILIES,
  FONT_FAMILY_KEYS,
  HEX_COLOR_PATTERN,
  MAX_ACTIVE_LOCALES,
  MAX_BRANDING_BYTES,
  MAX_LOCALE_TAG_LENGTH,
  MAX_ORGANIZATION_NAME_LENGTH,
  MIN_INSTALLABLE_ICON_PX,
  PUSH_MODULE_KEY,
  SETUP_TOKEN_HEADER,
  SHIPPED_APP_ICONS,
  WEB_MANIFEST_MIME_TYPE,
  WEB_MANIFEST_PATH,
  brandingTypeSummary,
  canonicalLocaleTag,
  fontFamilyStack,
  isBrandingImageKind,
  isFontFamilyKey,
  isHexColor,
  isLocaleTag,
  pluginElementId,
  type AppConfig,
  type AppConfigChange,
  type AppConfigSettings,
  type BrandingImageKind,
  type BrandingImages,
  type FontFamilyOption,
  type LocaleSettings,
  type LogoImage,
  type ModuleFamily,
  type ModuleSummary,
  type ModuleToggle,
  type PluginDescriptor,
  type PluginMountPoint,
  type SetupResult,
  type SetupState,
  type SetupSubmission,
  type Theme,
  type WebManifest,
  type WebManifestIcon,
} from './lib/config';
