/**
 * Models shared by the server and both clients.
 *
 * Framework-free on purpose: the NestJS server, the participant client and the
 * organizer client all compile against these types, so a change to an API
 * contract breaks the build instead of a request at runtime.
 */
export type {
  AdminAccount,
  AdminLoginRequest,
  AdminSessionInfo,
} from './lib/auth';
export {
  EVENT_SERIES_STATUSES,
  EVENT_STATUSES,
  EVENT_TYPES,
  dayInZone,
  formatClockRange,
  formatDayInZone,
  formatEventPeriod,
  formatInstant,
  hasEnded,
  instantToWallClock,
  isTimeZone,
  localTimeZone,
  wallClockToInstant,
  zoneLabel,
  type EventInput,
  type EventPeriod,
  type EventSeries,
  type EventSeriesInput,
  type EventSeriesStatus,
  type EventStatus,
  type EventType,
  type OrganizerEvent,
  type PublicEvent,
  type PublicEventSeries,
} from './lib/events';
export {
  DEFAULT_PARTICIPANT_PAGE_SIZE,
  DEFAULT_PARTICIPANT_SORT,
  DEFAULT_SORT_DIRECTION,
  DEFAULT_UPLOAD_MAX_BYTES,
  MAX_CUSTOM_TEXT_LENGTH,
  MAX_FIELD_HELP_LENGTH,
  MAX_FIELD_KEY_LENGTH,
  MAX_FIELD_LABEL_LENGTH,
  MAX_FIELD_OPTIONS,
  MAX_FIELD_OPTION_LENGTH,
  MAX_FILE_FIELDS,
  MAX_FILE_NAME_LENGTH,
  MAX_PARTICIPANT_PAGE_SIZE,
  MAX_REGISTRATION_FIELDS,
  MAX_SUBMISSION_BYTES,
  MAX_UPLOAD_BYTES,
  MIN_UPLOAD_MAX_BYTES,
  PARTICIPANT_SORTS,
  REGISTRATION_FIELD_TYPES,
  REGISTRATION_PAYLOAD_PART,
  REGISTRATION_STATUSES,
  UPLOAD_MIME_TYPES,
  UPLOAD_TYPES,
  acceptAttribute,
  formatAnswer,
  formatBytes,
  pageCount,
  uploadTypeLabel,
  type AttachmentSummary,
  type ConfirmationState,
  type CustomFieldValue,
  type CustomFieldValues,
  type ParticipantDetail,
  type ParticipantPage,
  type ParticipantQuery,
  type ParticipantRow,
  type ParticipantSort,
  type RegistrationAcknowledgement,
  type RegistrationConfirmation,
  type RegistrationCounts,
  type RegistrationField,
  type RegistrationFieldChange,
  type RegistrationFieldInput,
  type RegistrationFieldOrder,
  type RegistrationFieldPublic,
  type RegistrationFieldType,
  type RegistrationInput,
  type RegistrationStatistics,
  type RegistrationStatus,
  type RegistrationStatusChange,
  type RegistrationWeek,
  type SortDirection,
  type UploadType,
} from './lib/registrations';
export {
  MAX_PROGRAM_DESCRIPTION_LENGTH,
  MAX_PROGRAM_ITEMS,
  MAX_PROGRAM_SPEAKER_LENGTH,
  MAX_PROGRAM_TITLE_LENGTH,
  formatProgramTime,
  groupProgramByDay,
  isWithinPeriod,
  overlappingProgramItems,
  sortProgram,
  type ProgramDay,
  type ProgramItem,
  type ProgramItemChange,
  type ProgramItemInput,
  type PublicProgramItem,
} from './lib/program';
export type {
  AppConfig,
  PluginDescriptor,
  PluginMountPoint,
  Theme,
} from './lib/config';
