/**
 * Models shared by the server and both clients.
 *
 * Framework-free on purpose: the NestJS server, the participant client and the
 * organizer client all compile against these types, so a change to an API
 * contract breaks the build instead of a request at runtime.
 */
export type {
  AdminAccount,
  AdminLoginRequest,
  AdminSessionInfo,
} from './lib/auth';
export {
  EVENT_SERIES_STATUSES,
  EVENT_STATUSES,
  EVENT_TYPES,
  MAX_FOLLOW_UP_LENGTH,
  dayInZone,
  formatClockRange,
  formatDayInZone,
  formatEventPeriod,
  formatInstant,
  hasEnded,
  instantToWallClock,
  isTimeZone,
  localTimeZone,
  publicEventPath,
  wallClockToInstant,
  zoneLabel,
  type EventInput,
  type EventPeriod,
  type EventSeries,
  type EventSeriesInput,
  type EventSeriesStatus,
  type EventStatus,
  type EventType,
  type OrganizerEvent,
  type PublicEvent,
  type PublicEventSeries,
} from './lib/events';
export {
  DASHBOARD_LATEST_REGISTRATIONS,
  type EventDashboard,
  type ProgramSummary,
  type RegistrationFormSummary,
} from './lib/dashboard';
export {
  DEFAULT_PARTICIPANT_PAGE_SIZE,
  DEFAULT_PARTICIPANT_SORT,
  DEFAULT_SORT_DIRECTION,
  DEFAULT_UPLOAD_MAX_BYTES,
  MAX_CUSTOM_TEXT_LENGTH,
  MAX_FIELD_HELP_LENGTH,
  MAX_FIELD_KEY_LENGTH,
  MAX_FIELD_LABEL_LENGTH,
  MAX_FIELD_OPTIONS,
  MAX_FIELD_OPTION_LENGTH,
  MAX_FILE_FIELDS,
  MAX_FILE_NAME_LENGTH,
  MAX_PARTICIPANT_PAGE_SIZE,
  MAX_REGISTRATION_FIELDS,
  MAX_SUBMISSION_BYTES,
  MAX_UPLOAD_BYTES,
  MIN_UPLOAD_MAX_BYTES,
  PARTICIPANT_SORTS,
  REGISTRATION_FIELD_TYPES,
  REGISTRATION_PAYLOAD_PART,
  REGISTRATION_STATUSES,
  UPLOAD_MIME_TYPES,
  UPLOAD_TYPES,
  acceptAttribute,
  formatAnswer,
  formatBytes,
  pageCount,
  uploadTypeLabel,
  type AttachmentSummary,
  type ConfirmationState,
  type CustomFieldValue,
  type CustomFieldValues,
  type ParticipantDetail,
  type ParticipantPage,
  type ParticipantQuery,
  type ParticipantRow,
  type ParticipantSort,
  type RegistrationAcknowledgement,
  type RegistrationConfirmation,
  type RegistrationCounts,
  type RegistrationField,
  type RegistrationFieldChange,
  type RegistrationFieldInput,
  type RegistrationFieldOrder,
  type RegistrationFieldPublic,
  type RegistrationFieldType,
  type RegistrationInput,
  type RegistrationStatistics,
  type RegistrationStatus,
  type RegistrationStatusChange,
  type RegistrationWeek,
  type SortDirection,
  type UploadType,
} from './lib/registrations';
export {
  MAX_MEDIA_LINKS_PER_EVENT,
  MAX_MEDIA_LINK_TITLE_LENGTH,
  MAX_MEDIA_LINK_URL_LENGTH,
  MEDIA_LINKS_MODULE_KEY,
  MEDIA_LINK_KINDS,
  MEDIA_LINK_KIND_LABELS,
  eventMediaLinks,
  groupMediaLinksByKind,
  isWebUrl,
  mediaLinkKindLabel,
  programItemMediaLinks,
  sortMediaLinks,
  type MediaLink,
  type MediaLinkChange,
  type MediaLinkGroup,
  type MediaLinkInput,
  type MediaLinkKind,
  type MediaLinkKindLabel,
  type MediaLinkSummary,
  type PublicMediaLink,
} from './lib/media-links';
export {
  DEFAULT_CONTACT_PAGE_SIZE,
  DEFAULT_INVITATION_PAGE_SIZE,
  INVITATION_OPT_OUT_PATH,
  MAX_CONTACT_PAGE_SIZE,
  MAX_INVITATION_BODY_LENGTH,
  MAX_INVITATION_PAGE_SIZE,
  MAX_INVITATION_RECIPIENTS,
  MAX_INVITATION_SUBJECT_LENGTH,
  invitationParagraphs,
  invitationState,
  type ContactOptOutResult,
  type ContactQuery,
  type Invitation,
  type InvitationCounts,
  type InvitationInput,
  type InvitationPage,
  type InvitationQuery,
  type InvitationState,
  type SeriesContact,
  type SeriesContactPage,
} from './lib/invitations';
export {
  MAX_PROGRAM_DESCRIPTION_LENGTH,
  MAX_PROGRAM_ITEMS,
  MAX_PROGRAM_ITEM_CAPACITY,
  MAX_PROGRAM_SPEAKER_LENGTH,
  MAX_PROGRAM_TITLE_LENGTH,
  formatProgramTime,
  groupProgramByDay,
  isProgramItemFull,
  isWithinPeriod,
  overlappingProgramItems,
  seatsLeft,
  sortProgram,
  type ProgramDay,
  type ProgramItem,
  type ProgramItemChange,
  type ProgramItemInput,
  type ProgramItemLoad,
  type ProgramItemSignup,
  type PublicProgramItem,
} from './lib/program';
export {
  SELF_SERVICE_PATH,
  type MyProgramItem,
  type MyRegistration,
} from './lib/self-service';
export {
  BRANDING_IMAGE_KINDS,
  BRANDING_IMAGE_PART,
  BRANDING_MIME_TYPES,
  BRANDING_TYPES,
  DEFAULT_FONT_FAMILY_KEY,
  DEFAULT_FONT_FAMILY_STACK,
  DEFAULT_ORGANIZATION_NAME,
  FONT_FAMILIES,
  FONT_FAMILY_KEYS,
  HEX_COLOR_PATTERN,
  MAX_BRANDING_BYTES,
  MAX_LOCALE_TAG_LENGTH,
  MAX_ORGANIZATION_NAME_LENGTH,
  PUSH_MODULE_KEY,
  SETUP_TOKEN_HEADER,
  brandingTypeSummary,
  fontFamilyStack,
  isBrandingImageKind,
  isFontFamilyKey,
  isHexColor,
  moduleDisplayName,
  pluginElementId,
  type AppConfig,
  type AppConfigChange,
  type AppConfigSettings,
  type BrandingImageKind,
  type BrandingImages,
  type FontFamilyOption,
  type ModuleFamily,
  type ModuleSummary,
  type ModuleToggle,
  type PluginDescriptor,
  type PluginMountPoint,
  type SetupResult,
  type SetupState,
  type SetupSubmission,
  type Theme,
} from './lib/config';
