export {
  DEFAULT_PROPOSAL_PAGE_SIZE,
  MAX_PROPOSAL_DESCRIPTION_LENGTH,
  MAX_PROPOSAL_PAGE_SIZE,
  MAX_PROPOSAL_TITLE_LENGTH,
  PROGRAM_PROPOSALS_MODULE_KEY,
  PROPOSAL_STATUSES,
  type NewProgramProposal,
  type ProgramProposal,
  type ProposalAuthor,
  type ProposalPage,
  type ProposalQuery,
  type ProposalStatus,
  type ProposalSummary,
} from './program-proposals';
