/**
 * Port for the check-in plug-in's storage (FR 3.16): one row per registration.
 *
 * Small, because the plug-in is: a code is issued once, read at a door, and
 * looked up in batches for the admission list. What the port deliberately does
 * not offer is a way to read a registration or an event — both are core tables
 * the plug-in owns nothing of (F21), and what it knows about who is expected
 * arrives through `PluginRegistrationReads`.
 *
 * Two rules live in the statements rather than in a caller (F152):
 *
 * - **Issuing is idempotent.** {@link issue} inserts on conflict do nothing and
 *   reads the row back, so two tabs opening the same ticket page cannot end up
 *   with two codes — and the second one does not get an error either, because
 *   there is nothing wrong with it.
 * - **The door writes once.** {@link checkIn} sets `checked_in_at` only where
 *   it is still NULL, and answers with the row as it now stands **and with
 *   whether this call was the one that wrote it**. A second scan therefore
 *   reads back the first instant rather than overwriting it, and the service
 *   learns "already here" from the statement rather than by comparing two
 *   timestamps above the database.
 */

/** One ticket as the business layer sees it — no ORM types. */
export interface TicketRecord {
  readonly registrationId: string;
  readonly code: string;
  readonly issuedAt: Date;
  /** `null` while they have not arrived. */
  readonly checkedInAt: Date | null;
  readonly checkedInBy: string | null;
}

/** What issuing a ticket needs: the row it is for, and the code to give it. */
export interface IssueTicketInput {
  readonly registrationId: string;
  /** Already generated by the service; the database only stores it. */
  readonly code: string;
  readonly issuedAt: Date;
}

/**
 * Raised when the registration a ticket is issued for does not exist.
 *
 * Narrow on purpose: the foreign key cascades, so this is a registration
 * deleted between reading the list and issuing the code. The data access layer
 * translates the constraint violation into this error so the business layer can
 * answer 404 rather than 500 — the driver's error code stays where the ORM
 * does.
 */
export class UnknownTicketRegistrationError extends Error {
  constructor(readonly registrationId: string) {
    super('No such registration');
    this.name = 'UnknownTicketRegistrationError';
  }
}

/** What one scan did, and to which row. */
export interface AdmissionResult {
  readonly ticket: TicketRecord;
  /**
   * True when this call recorded the admission.
   *
   * False means somebody was already here — which is an answer, not an error
   * (E53). It comes from the number of rows the conditional update touched, so
   * two phones scanning at once cannot both be told they were first.
   */
  readonly admitted: boolean;
}

export interface TicketRepository {
  /**
   * The tickets of these registrations, keyed by registration id.
   *
   * Many ids in one call rather than one call per row, because every caller is
   * rendering a list (F49). An id with no ticket yet is simply absent.
   */
  findMany(
    registrationIds: readonly string[],
  ): Promise<ReadonlyMap<string, TicketRecord>>;

  /**
   * Issues tickets for these registrations, or reads back the ones that exist.
   *
   * One statement for a whole page: a code is created on first read (E53), and
   * "first read" is as true of an admission list as it is of a ticket page —
   * the button beside a row has to send the same code the camera would read
   * (F199), so a row without one would be a row the door cannot use.
   *
   * Idempotent by the primary key: issuing again returns what is already there
   * and never a second code.
   *
   * @throws UnknownTicketRegistrationError
   */
  issue(
    inputs: readonly IssueTicketInput[],
  ): Promise<ReadonlyMap<string, TicketRecord>>;

  /** The ticket carrying this code, or `null`. */
  findByCode(code: string): Promise<TicketRecord | null>;

  /**
   * Records an admission, once (E53).
   *
   * Writes `checked_in_at` only where it is still NULL and answers with the row
   * as it now stands, plus whether this call was the one that wrote it — so a
   * second scan reads back the first instant instead of moving it, and the
   * caller needs no compare-and-set of its own. `null` when no ticket carries
   * that code.
   */
  checkIn(
    code: string,
    checkedInAt: Date,
    checkedInBy: string,
  ): Promise<AdmissionResult | null>;
}

export const TICKET_REPOSITORY = Symbol('TREFARO_TICKET_REPOSITORY');
